Name=input("enter your name:")
dept=input("enter your department:")
year=input("enter your pursuing year:")
college=input("enter your college name:")
print(Name)
print(dept)
print(year)
print(college)